# 🚀 This workflow handles deployment when you create a release
# It automatically packages your app and uploads it as a release asset

name: Deploy Release

# This workflow only runs when you create a new release or push a tag
on:
  release:
    types: [published] # Runs when you publish a release on GitHub
  push:
    tags:
      - "v*" # Runs when you push a tag like v1.0.0, v2.1.3, etc.

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to upload files to releases

    steps:
      # Step 1: Download your code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests one more time (safety check before release)
      - name: Run tests before deploying
        run: |
          pytest --cov=main
        # 🧠 If tests fail, the deployment stops here. No broken releases!

      # Step 5: Create a distributable package
      - name: Create distribution package
        run: |
          # Create a folder for the release
          mkdir -p dist
          # Copy your main files to the dist folder
          cp main.py dist/
          cp README.md dist/
          cp requirements.txt dist/
          # Create a zip file
          cd dist
          zip -r ../auto-todo-${{ github.ref_name }}.zip .
          cd ..
        # 🧠 This creates a .zip file named after your tag (e.g., auto-todo-v1.0.0.zip)

      # Step 6: Upload the .zip to the GitHub Release
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./auto-todo-${{ github.ref_name }}.zip
          asset_name: auto-todo-${{ github.ref_name }}.zip
          asset_content_type: application/zip
        # 🧠 This attaches the .zip file to your GitHub Release
        # 🧠 GITHUB_TOKEN is automatically provided by GitHub (no setup needed)
